### ISSUE TITLE
Partition storage accounts contain a 'opendes' container regardless of the data partitions provided

### ISSUE THREAD

**Issue by Kyle-MSFT** [Azure/osdu-bicep#100]
I created 3 partitions (opendes, mine, anotherone). I see 3 storage accounts, one for each partition, but they all contain the opendes container. This is because the opendes container name is hard coded in partitionLayerConfig in main.bicep

![image](https://user-images.githubusercontent.com/62899600/205105401-2e0ff0b2-8ca4-48a3-b60a-a2c48ee98487.png)

Managed App Instance w/ issue: datapartitiontest

**Comment by danielscholl** [comment]
This is a direct copy from OSDU. So until I run the code not sure it is an error. 

https://community.opengroup.org/osdu/platform/deployment-and-operations/infra-azure-provisioning/-/blob/master/infra/templates/osdu-r3-mvp/data_partition/terraform.tfvars#L42-L49

**Comment by danielscholl** [comment]
Looked at the implementation. Taking in the change it makes sense.
