### ISSUE TITLE
Create App Configuration Module

### ISSUE THREAD

**Issue by ianphil** [Azure/osdu-bicep#54]
Follow current pattern set by other modules. This will be used for feature flags, key vault integration, and key/value store. 

 1. App Configuration Store + key/value -> COMPLETED
 2. Feature Managment
 3. Key Vault integration

Ref:
 - https://learn.microsoft.com/en-us/azure/azure-app-configuration/quickstart-bicep?tabs=CLI
 - https://github.com/Azure/azure-quickstart-templates/tree/da0cdd93d7dd7d842c9c7e89738d4682c8013495/quickstarts/microsoft.appconfiguration

**Comment by ianphil** [comment]
Reopening so we can complete the last two items in this list... Feature flags and Key Vault ref.

**Comment by danielscholl** [comment]
Completed.
