### ISSUE TITLE
Add Key Vault References

### ISSUE THREAD

**Issue by saadmanMS** [Azure/osdu-bicep#78]
We want to test and add key vault references to the existing app config module creates in Issue #54 

Other links:
- PBI: https://dev.azure.com/OpenEnergyPlatform/Open%20Energy%20Platform/_workitems/edit/15725/
- KeyVault reference bicep: https://github.com/Azure/azure-quickstart-templates/tree/da0cdd93d7dd7d842c9c7e89738d4682c8013495/quickstarts/microsoft.appconfiguration/app-configuration-store-keyvaultref

**Comment by danielscholl** [comment]
Implemented.
